export const BakeryItems = [
  { id: 1, imageUrl: "/white_bread.png", title: "White Bread", price: "$2.49", category: "Bread" },
  { id: 2, imageUrl: "/baguette.png", title: "Baguette", price: "$1.99", category: "Bread" },
  { id: 3, imageUrl: "/croissant.png", title: "Croissant", price: "$2.29", category: "Baked Goods" },
  { id: 4, imageUrl: "/muffin.png", title: "Muffin", price: "$1.79", category: "Baked Goods" },
  { id: 5, imageUrl: "/sourdough.png", title: "Sourdough Bread", price: "$3.49", category: "Bread" },
  { id: 6, imageUrl: "/whole_wheat_bread.png", title: "Whole Wheat Bread", price: "$2.99", category: "Bread" },
  { id: 7, imageUrl: "/doughnuts.png", title: "Doughnuts", price: "$3.99", category: "Baked Goods" },
  { id: 8, imageUrl: "/cupcake.png", title: "Cupcake", price: "$1.99", category: "Baked Goods" },
  { id: 9, imageUrl: "/bagel.png", title: "Bagel", price: "$1.29", category: "Bread" },
  { id: 10, imageUrl: "/pita_bread.png", title: "Pita Bread", price: "$2.59", category: "Bread" },
  { id: 11, imageUrl: "/brioche.png", title: "Brioche", price: "$3.29", category: "Bread" },
  { id: 12, imageUrl: "/ciabatta.png", title: "Ciabatta", price: "$3.79", category: "Bread" },
  { id: 13, imageUrl: "/baking_powder.png", title: "Baking Powder", price: "$1.19", category: "Baking Ingredients" },
  { id: 14, imageUrl: "/flour.png", title: "All-Purpose Flour", price: "$2.49", category: "Baking Ingredients" },
  { id: 15, imageUrl: "/sugar.png", title: "Granulated Sugar", price: "$1.99", category: "Baking Ingredients" },
  { id: 16, imageUrl: "/yeast.png", title: "Active Dry Yeast", price: "$1.79", category: "Baking Ingredients" },
  { id: 17, imageUrl: "/brown_sugar.png", title: "Brown Sugar", price: "$2.29", category: "Baking Ingredients" },
  { id: 18, imageUrl: "/baking_soda.png", title: "Baking Soda", price: "$0.99", category: "Baking Ingredients" },
  { id: 19, imageUrl: "/vanilla_extract.png", title: "Vanilla Extract", price: "$3.99", category: "Baking Ingredients" },
  { id: 20, imageUrl: "/cocoa_powder.png", title: "Cocoa Powder", price: "$2.99", category: "Baking Ingredients" },
  { id: 21, imageUrl: "/chocolate_chips.png", title: "Chocolate Chips", price: "$2.79", category: "Baking Ingredients" },
  { id: 22, imageUrl: "/cake_mix.png", title: "Cake Mix", price: "$4.49", category: "Baking Ingredients" },
  { id: 23, imageUrl: "/cornstarch.png", title: "Cornstarch", price: "$1.49", category: "Baking Ingredients" },
  { id: 24, imageUrl: "/buttermilk.png", title: "Buttermilk", price: "$2.99", category: "Baking Ingredients" },
  { id: 25, imageUrl: "/pie_crust.png", title: "Pie Crust", price: "$3.29", category: "Baking Ingredients" },
  { id: 26, imageUrl: "/puff_pastry.png", title: "Puff Pastry", price: "$4.99", category: "Baking Ingredients" },
  { id: 27, imageUrl: "/cinnamon.png", title: "Ground Cinnamon", price: "$1.69", category: "Baking Ingredients" },
  { id: 28, imageUrl: "/honey.png", title: "Honey", price: "$5.49", category: "Baking Ingredients" },
  { id: 29, imageUrl: "/molasses.png", title: "Molasses", price: "$3.49", category: "Baking Ingredients" },
  { id: 30, imageUrl: "/shortening.png", title: "Shortening", price: "$3.79", category: "Baking Ingredients" },
  { id: 31, imageUrl: "/buttercream_frosting.png", title: "Buttercream Frosting", price: "$3.99", category: "Baking Ingredients" },
  { id: 32, imageUrl: "/powdered_sugar.png", title: "Powdered Sugar", price: "$1.89", category: "Baking Ingredients" },
  { id: 33, imageUrl: "/gluten_free_flour.png", title: "Gluten-Free Flour", price: "$4.29", category: "Baking Ingredients" },
  { id: 34, imageUrl: "/whole_grain_flour.png", title: "Whole Grain Flour", price: "$3.99", category: "Baking Ingredients" },
  { id: 35, imageUrl: "/sliced_bread.png", title: "Sliced Bread", price: "$2.79", category: "Bread" },
  { id: 36, imageUrl: "/raisin_bread.png", title: "Raisin Bread", price: "$3.29", category: "Bread" },
  { id: 37, imageUrl: "/apple_pie.png", title: "Apple Pie", price: "$5.99", category: "Baked Goods" },
  { id: 38, imageUrl: "/baking_chocolate.png", title: "Baking Chocolate", price: "$3.99", category: "Baking Ingredients" },
  { id: 39, imageUrl: "/sprinkles.png", title: "Sprinkles", price: "$2.49", category: "Baking Ingredients" },
  { id: 40, imageUrl: "/oats.png", title: "Rolled Oats", price: "$2.29", category: "Baking Ingredients" },
  { id: 41, imageUrl: "/marshmallows.png", title: "Marshmallows", price: "$1.99", category: "Baking Ingredients" }
];
