export const BakeryItems = [
    { imageUrl: "/white_bread.png", title: "White Bread", price: "$2.49" },
    { imageUrl: "/baguette.png", title: "Baguette", price: "$1.99" },
    { imageUrl: "/croissant.png", title: "Croissant", price: "$2.29" },
    { imageUrl: "/muffin.png", title: "Muffin", price: "$1.79" },
    { imageUrl: "/sourdough.png", title: "Sourdough Bread", price: "$3.49" },
    { imageUrl: "/whole_wheat_bread.png", title: "Whole Wheat Bread", price: "$2.99" },
    { imageUrl: "/doughnuts.png", title: "Doughnuts", price: "$3.99" },
    { imageUrl: "/cupcake.png", title: "Cupcake", price: "$1.99" },
    { imageUrl: "/bagel.png", title: "Bagel", price: "$1.29" },
    { imageUrl: "/pita_bread.png", title: "Pita Bread", price: "$2.59" },
    { imageUrl: "/brioche.png", title: "Brioche", price: "$3.29" },
    { imageUrl: "/ciabatta.png", title: "Ciabatta", price: "$3.79" },
    { imageUrl: "/baking_powder.png", title: "Baking Powder", price: "$1.19" },
    { imageUrl: "/flour.png", title: "All-Purpose Flour", price: "$2.49" },
    { imageUrl: "/sugar.png", title: "Granulated Sugar", price: "$1.99" },
    { imageUrl: "/yeast.png", title: "Active Dry Yeast", price: "$1.79" },
    { imageUrl: "/brown_sugar.png", title: "Brown Sugar", price: "$2.29" },
    { imageUrl: "/baking_soda.png", title: "Baking Soda", price: "$0.99" },
    { imageUrl: "/vanilla_extract.png", title: "Vanilla Extract", price: "$3.99" },
    { imageUrl: "/cocoa_powder.png", title: "Cocoa Powder", price: "$2.99" },
    { imageUrl: "/chocolate_chips.png", title: "Chocolate Chips", price: "$2.79" },
    { imageUrl: "/cake_mix.png", title: "Cake Mix", price: "$4.49" },
    { imageUrl: "/cornstarch.png", title: "Cornstarch", price: "$1.49" },
    { imageUrl: "/buttermilk.png", title: "Buttermilk", price: "$2.99" },
    { imageUrl: "/pie_crust.png", title: "Pie Crust", price: "$3.29" },
    { imageUrl: "/puff_pastry.png", title: "Puff Pastry", price: "$4.99" },
    { imageUrl: "/cinnamon.png", title: "Ground Cinnamon", price: "$1.69" },
    { imageUrl: "/honey.png", title: "Honey", price: "$5.49" },
    { imageUrl: "/molasses.png", title: "Molasses", price: "$3.49" },
    { imageUrl: "/shortening.png", title: "Shortening", price: "$3.79" },
    { imageUrl: "/buttercream_frosting.png", title: "Buttercream Frosting", price: "$3.99" },
    { imageUrl: "/powdered_sugar.png", title: "Powdered Sugar", price: "$1.89" },
    { imageUrl: "/gluten_free_flour.png", title: "Gluten-Free Flour", price: "$4.29" },
    { imageUrl: "/whole_grain_flour.png", title: "Whole Grain Flour", price: "$3.99" },
    { imageUrl: "/sliced_bread.png", title: "Sliced Bread", price: "$2.79" },
    { imageUrl: "/raisin_bread.png", title: "Raisin Bread", price: "$3.29" },
    { imageUrl: "/apple_pie.png", title: "Apple Pie", price: "$5.99" },
    { imageUrl: "/baking_chocolate.png", title: "Baking Chocolate", price: "$3.99" },
    { imageUrl: "/sprinkles.png", title: "Sprinkles", price: "$2.49" },
    { imageUrl: "/oats.png", title: "Rolled Oats", price: "$2.29" },
    { imageUrl: "/marshmallows.png", title: "Marshmallows", price: "$1.99" }
];
