export const BeveragesItems = [
    { imageUrl: "/orange_juice.png", title: "Orange Juice", price: "$3.49" },
    { imageUrl: "/apple_juice.png", title: "Apple Juice", price: "$2.99" },
    { imageUrl: "/lemonade.png", title: "Lemonade", price: "$1.99" },
    { imageUrl: "/iced_tea.png", title: "Iced Tea", price: "$2.79" },
    { imageUrl: "/coffee.png", title: "Coffee", price: "$4.99" },
    { imageUrl: "/black_tea.png", title: "Black Tea", price: "$2.49" },
    { imageUrl: "/green_tea.png", title: "Green Tea", price: "$3.29" },
    { imageUrl: "/soda.png", title: "Soda", price: "$1.49" },
    { imageUrl: "/cola.png", title: "Cola", price: "$1.59" },
    { imageUrl: "/energy_drink.png", title: "Energy Drink", price: "$2.99" },
    { imageUrl: "/sports_drink.png", title: "Sports Drink", price: "$2.79" },
    { imageUrl: "/bottled_water.png", title: "Bottled Water", price: "$0.99" },
    { imageUrl: "/sparkling_water.png", title: "Sparkling Water", price: "$1.89" },
    { imageUrl: "/milkshake.png", title: "Milkshake", price: "$3.99" },
    { imageUrl: "/smoothie.png", title: "Smoothie", price: "$4.29" },
    { imageUrl: "/hot_chocolate.png", title: "Hot Chocolate", price: "$2.49" },
    { imageUrl: "/coconut_water.png", title: "Coconut Water", price: "$2.19" },
    { imageUrl: "/grape_juice.png", title: "Grape Juice", price: "$3.49" },
    { imageUrl: "/cranberry_juice.png", title: "Cranberry Juice", price: "$2.89" },
    { imageUrl: "/tomato_juice.png", title: "Tomato Juice", price: "$2.19" },
    { imageUrl: "/chai_latte.png", title: "Chai Latte", price: "$3.99" },
    { imageUrl: "/herbal_tea.png", title: "Herbal Tea", price: "$2.69" },
    { imageUrl: "/espresso.png", title: "Espresso", price: "$5.49" },
    { imageUrl: "/latte.png", title: "Latte", price: "$4.79" },
    { imageUrl: "/beer.png", title: "Beer", price: "$6.99" },
    { imageUrl: "/wine.png", title: "Wine", price: "$14.99" },
    { imageUrl: "/whiskey.png", title: "Whiskey", price: "$19.99" },
    { imageUrl: "/vodka.png", title: "Vodka", price: "$16.99" },
    { imageUrl: "/rum.png", title: "Rum", price: "$17.49" },
    { imageUrl: "/gin.png", title: "Gin", price: "$18.99" },
    { imageUrl: "/champagne.png", title: "Champagne", price: "$29.99" }
];
