
export const BeveragesItems = [
  { id: 43, imageUrl: "/orange_juice.png", title: "Orange Juice", price: "$3.49" },
  { id: 44, imageUrl: "/apple_juice.png", title: "Apple Juice", price: "$2.99" },
  { id: 45, imageUrl: "/lemonade.png", title: "Lemonade", price: "$1.99" },
  { id: 46, imageUrl: "/iced_tea.png", title: "Iced Tea", price: "$2.79" },
  { id: 47, imageUrl: "/coffee.png", title: "Coffee", price: "$4.99" },
  { id: 48, imageUrl: "/black_tea.png", title: "Black Tea", price: "$2.49" },
  { id: 49, imageUrl: "/green_tea.png", title: "Green Tea", price: "$3.29" },
  { id: 50, imageUrl: "/soda.png", title: "Soda", price: "$1.49" },
  { id: 51, imageUrl: "/cola.png", title: "Cola", price: "$1.59" },
  { id: 52, imageUrl: "/energy_drink.png", title: "Energy Drink", price: "$2.99" },
  { id: 53, imageUrl: "/sports_drink.png", title: "Sports Drink", price: "$2.79" },
  { id: 54, imageUrl: "/bottled_water.png", title: "Bottled Water", price: "$0.99" },
  { id: 55, imageUrl: "/sparkling_water.png", title: "Sparkling Water", price: "$1.89" },
  { id: 56, imageUrl: "/milkshake.png", title: "Milkshake", price: "$3.99" },
  { id: 57, imageUrl: "/smoothie.png", title: "Smoothie", price: "$4.29" },
  { id: 58, imageUrl: "/hot_chocolate.png", title: "Hot Chocolate", price: "$2.49" },
  { id: 59, imageUrl: "/coconut_water.png", title: "Coconut Water", price: "$2.19" },
  { id: 60, imageUrl: "/grape_juice.png", title: "Grape Juice", price: "$3.49" },
  { id: 61, imageUrl: "/cranberry_juice.png", title: "Cranberry Juice", price: "$2.89" },
  { id: 62, imageUrl: "/tomato_juice.png", title: "Tomato Juice", price: "$2.19" },
  { id: 63, imageUrl: "/chai_latte.png", title: "Chai Latte", price: "$3.99" },
  { id: 64, imageUrl: "/herbal_tea.png", title: "Herbal Tea", price: "$2.69" },
  { id: 65, imageUrl: "/espresso.png", title: "Espresso", price: "$5.49" },
  { id: 66, imageUrl: "/latte.png", title: "Latte", price: "$4.79" },
  { id: 67, imageUrl: "/beer.png", title: "Beer", price: "$6.99" },
  { id: 68, imageUrl: "/wine.png", title: "Wine", price: "$14.99" },
  { id: 69, imageUrl: "/whiskey.png", title: "Whiskey", price: "$19.99" },
  { id: 70, imageUrl: "/vodka.png", title: "Vodka", price: "$16.99" },
  { id: 71, imageUrl: "/rum.png", title: "Rum", price: "$17.49" },
  { id: 72, imageUrl: "/gin.png", title: "Gin", price: "$18.99" },
  { id: 73, imageUrl: "/champagne.png", title: "Champagne", price: "$29.99" }
];
