export const DairyProductsItems = [
  { id: 74, imageUrl: "/milk.png", title: "Milk", price: "$2.49" },
  { id: 75, imageUrl: "/cheddar_cheese.png", title: "Cheddar Cheese", price: "$4.99" },
  { id: 76, imageUrl: "/yogurt.png", title: "Yogurt", price: "$1.99" },
  { id: 77, imageUrl: "/butter.png", title: "Butter", price: "$3.49" },
  { id: 78, imageUrl: "/sour_cream.png", title: "Sour Cream", price: "$2.29" },
  { id: 79, imageUrl: "/cream_cheese.png", title: "Cream Cheese", price: "$2.99" },
  { id: 80, imageUrl: "/mozzarella_cheese.png", title: "Mozzarella Cheese", price: "$4.49" },
  { id: 81, imageUrl: "/cottage_cheese.png", title: "Cottage Cheese", price: "$3.79" },
  { id: 82, imageUrl: "/whipping_cream.png", title: "Whipping Cream", price: "$3.99" },
  { id: 83, imageUrl: "/parmesan_cheese.png", title: "Parmesan Cheese", price: "$5.49" },
  { id: 84, imageUrl: "/ice_cream.png", title: "Ice Cream", price: "$4.99" },
  { id: 85, imageUrl: "/almond_milk.png", title: "Almond Milk", price: "$2.99" },
  { id: 86, imageUrl: "/goat_cheese.png", title: "Goat Cheese", price: "$6.49" },
  { id: 87, imageUrl: "/greek_yogurt.png", title: "Greek Yogurt", price: "$3.29" },
  { id: 88, imageUrl: "/evaporated_milk.png", title: "Evaporated Milk", price: "$2.29" },
  { id: 89, imageUrl: "/powdered_milk.png", title: "Powdered Milk", price: "$5.99" },
  { id: 90, imageUrl: "/ricotta_cheese.png", title: "Ricotta Cheese", price: "$4.29" },
  { id: 91, imageUrl: "/soy_milk.png", title: "Soy Milk", price: "$2.49" },
  { id: 92, imageUrl: "/coconut_yogurt.png", title: "Coconut Yogurt", price: "$3.79" }
];
