export const FruitsAndVegetablesItem = [
  { id: 123, imageUrl: "/apple.png", title: "Apple", price: "$1.99", category: "Fruits" },
  { id: 124, imageUrl: "/banana.png", title: "Banana", price: "$0.99", category: "Fruits" },
  { id: 125, imageUrl: "/orange.png", title: "Orange", price: "$1.49", category: "Fruits" },
  { id: 126, imageUrl: "/grape.png", title: "Grapes", price: "$2.99", category: "Fruits" },
  { id: 127, imageUrl: "/carrot2.png", title: "Carrot", price: "$1.29", category: "Veggies" },
  { id: 128, imageUrl: "/tomato2.png", title: "Tomato", price: "$2.49", category: "Veggies" },
  { id: 129, imageUrl: "/potatoes.png", title: "Potato", price: "$0.79", category: "Veggies" },
  { id: 130, imageUrl: "/broccelli.png", title: "Broccoli", price: "$2.19", category: "Veggies" },
  { id: 131, imageUrl: "/lettuce1.png", title: "Lettuce", price: "$1.79", category: "Veggies" },
  { id: 132, imageUrl: "/onion.png", title: "Onion", price: "$1.09", category: "Veggies" },
  { id: 133, imageUrl: "/ballpapper.png", title: "Bell Pepper", price: "$1.59", category: "Veggies" },
  { id: 134, imageUrl: "/strawberry.png", title: "Strawberry", price: "$3.49", category: "Fruits" },
  { id: 135, imageUrl: "/watermelon.png", title: "Watermelon", price: "$5.99", category: "Fruits" },
  { id: 136, imageUrl: "/blueberry.png", title: "Blueberry", price: "$3.99", category: "Fruits" },
  { id: 137, imageUrl: "/cucumber.png", title: "Cucumber", price: "$0.89", category: "Veggies" },
  { id: 138, imageUrl: "/spinach.png", title: "Spinach", price: "$1.99", category: "Veggies" },
  { id: 139, imageUrl: "/Zucchini.png", title: "Zucchini", price: "$1.29", category: "Veggies" },
  { id: 140, imageUrl: "/kiwi.png", title: "Kiwi", price: "$1.19", category: "Fruits" },
  { id: 141, imageUrl: "/pine.png", title: "Pineapple", price: "$4.99", category: "Fruits" },
  { id: 142, imageUrl: "/mango.png", title: "Mango", price: "$2.49", category: "Fruits" }
];
