export const MeatAndSeafoodItems = [
  { id: 143, imageUrl: "/chicken_breast.png", title: "Chicken Breast", price: "$5.99" },
  { id: 144, imageUrl: "/beef_steak.png", title: "Beef Steak", price: "$12.99" },
  { id: 145, imageUrl: "/salmon_fillet.png", title: "Salmon Fillet", price: "$8.49" },
  { id: 146, imageUrl: "/pork_chop.png", title: "Pork Chop", price: "$6.99" },
  { id: 147, imageUrl: "/shrimp.png", title: "Shrimp", price: "$14.99" },
  { id: 148, imageUrl: "/lobster.png", title: "Lobster", price: "$29.99" },
  { id: 149, imageUrl: "/turkey_leg.png", title: "Turkey Leg", price: "$4.99" },
  { id: 150, imageUrl: "/crab.png", title: "Crab", price: "$21.99" },
  { id: 151, imageUrl: "/bacon.png", title: "Bacon", price: "$7.49" },
  { id: 152, imageUrl: "/tilapia.png", title: "Tilapia", price: "$5.29" },
  { id: 153, imageUrl: "/lamb_rack.png", title: "Lamb Rack", price: "$15.99" },
  { id: 154, imageUrl: "/tuna_steak.png", title: "Tuna Steak", price: "$10.49" },
  { id: 155, imageUrl: "/ground_beef.png", title: "Ground Beef", price: "$4.99" },
  { id: 156, imageUrl: "/scallops.png", title: "Scallops", price: "$18.99" },
  { id: 157, imageUrl: "/duck_breast.png", title: "Duck Breast", price: "$13.99" },
  { id: 158, imageUrl: "/cod_fillet.png", title: "Cod Fillet", price: "$7.99" },
  { id: 159, imageUrl: "/sausage.png", title: "Sausage", price: "$3.99" },
  { id: 160, imageUrl: "/clams.png", title: "Clams", price: "$9.99" },
  { id: 161, imageUrl: "/oysters.png", title: "Oysters", price: "$19.99" },
  { id: 162, imageUrl: "/king_crab.png", title: "King Crab", price: "$39.99" }
];
