export const PopularItems = [
    {
        id: 1,
        imageUrl: "/orange2.png",
        title: "Grape",
        price: "$2.99",
        rating: 4,
    },
    {
        id: 2,
        imageUrl: "/cabbage.png",
        title: "Cabbage",
        price: "$3.99",
        rating: 3,
    },
    {
        id: 3,
        imageUrl: "/apple.png",
        title: "Apple",
        price: "$1.99",
        rating: 5,
    },
    {
        id: 4,
        imageUrl: "/milk.png",
        title: "Milk",
        price: "$6.99",
        rating: 3,
    },
    {
        id: 5,
        imageUrl: "/grape.png",
        title: "Banana",
        price: "$0.99",
        rating: 3,
    },
    {
        id: 6,
        imageUrl: "/orange.png",
        title: "Mango",
        price: "$3.49",
        rating: 4,
    },
    {
        id: 7,
        imageUrl: "/fish.png",
        title: "Fish",
        price: "$8.99",
        rating: 3,
    },
    {
        id: 8,
        imageUrl: "/cabbage.png",
        title: "Cabbage",
        price: "$3.99",
        rating: 3,
    },
    {
        id: 9,
        imageUrl: "/broccelli.png",
        title: "Broccoli",
        price: "$0.99",
        rating: 3,
    },
    {
        id: 10,
        imageUrl: "/banana.png",
        title: "Banana",
        price: "$0.99",
        rating: 3,
    },
];
